[project]
name = "clean-folder"
version = "1.0.0"
authors = [
  { name="Sergii Olkhovskyi", email="programing.sergii@gmail.com" },
]
description = "A small example package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
